spring.application.name=shop

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/shop}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:shop}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.threads.virtual.enabled=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never