spring.jpa.show-sql=false

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

spring.flyway.placeholders.seed_demo_data=false
spring.flyway.baseline-on-migrate=false
spring.flyway.out-of-order=false
spring.flyway.clean-disabled=true